spring:
  application:
    name: service-feign
  #zipkin
  zipkin:
    base-url: http://119.3.177.94:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 8765

eureka:
  client:
    serviceUrl:
      #注册中心地址
      defaultZone: http://localhost:8761/eureka/

#  Feign是自带断路器的，在D版本的Spring Cloud之后，它没有默认打开
feign:
  hystrix:
    enabled: true