spring:
  application:
    name: eureka-client
  #zipkin
  zipkin:
    base-url: http://119.3.177.94:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0

server:
#  port: 8762
  port: 8763

eureka:
  client:
    serviceUrl:
      #注册中心地址
      defaultZone: http://localhost:8761/eureka/