spring:
  application:
    name: service-gateway
  #zipkin
  zipkin:
    base-url: http://119.3.177.94:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 8769

eureka:
  client:
    serviceUrl:
      #注册中心地址
      defaultZone: http://localhost:8761/eureka/